# theme: jekyll-theme-midnight
# remote_theme: riggraz/no-style-please 

# remote_theme: broccolini/swiss
# theme_color: black

remote_theme: just-the-docs/just-the-docs
title: Open Battle System
description: Bookmark this to keep an eye on my project updates!
github_username: openbattlesystem
github_repo: openbattlesystem.github.io 
timezone: America/New_York

# collections:
#   rules:
#     permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   collections:
#     rules:
#       name: Rules